version: '3.5'

services:
  postgres:
    container_name: pavshop_postgres_container
    image: postgres
    environment:
      POSTGRES_USER: pavshop_user
      POSTGRES_PASSWORD: pavshop_password
      POSTGRES_DB: shops_db
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped


networks:
  postgres:
    driver: bridge

volumes:
    postgres: