version: '3.5'

services:
  postgres:
    container_name: pavshop_postgres_container
    image: postgres
    environment:
      POSTGRES_USER: pavshop_user
      POSTGRES_PASSWORD: pavshop_password
      POSTGRES_DB: shops_db
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped
  

  web:
    container_name: pavshop
    build: .
    ports:
      - 8002:8000
    depends_on: 
      - "postgres"
      - "redis"
      
  

  celery:
    container_name: celery
    command: celery -A pavshop worker
    build: 
      context: .
      dockerfile: celery.dockerfile
    depends_on: 
      - "postgres"
      - "redis"
    env_file: .venv


  redis:
    image: redis
    restart: always
    ports:
      - 6379:6379


networks:
  postgres:
    driver: bridge

volumes:
    postgres: